import type { User } from "@/lib/types";

/**
 * Public user records — no passwords.
 * Plaintext credentials exist only as server-side hashes (see auth/credentials.ts).
 */
export const SEED_USERS: User[] = [
  {
    id: "babajide",
    name: "Babajide Arulogun",
    username: "DLUARU",
    role: "head",
    isSecretary: false,
    isCorps: false,
    color: "#8a6a1f",
    phone: "+234 703 319 8115",
    designation: "Head, Digital Learning Unit",
    gradeLevel: "GL 14",
    sex: "Male",
    stateOfOrigin: "Ogun",
    dateJoined: "2016-03-02",
    photoUrl: null,
  },
  {
    id: "benson",
    name: "Benson Ogunyemi",
    username: "DLUOGU",
    role: "member",
    isSecretary: false,
    isCorps: false,
    color: "#0e6b47",
    phone: "+234 70 3636 3381",
    designation: "Instructional Designer",
    gradeLevel: "GL 10",
    sex: "Male",
    stateOfOrigin: "Oyo",
    dateJoined: "2019-07-15",
    photoUrl: null,
  },
  {
    id: "agbaje",
    name: "Agbaje Ibrahim",
    username: "DLUIBR",
    role: "member",
    isSecretary: false,
    isCorps: false,
    color: "#9a4428",
    phone: "+234 70 1164 0728",
    designation: "LMS Content Officer",
    gradeLevel: "GL 09",
    sex: "Male",
    stateOfOrigin: "Kwara",
    dateJoined: "2020-01-20",
    photoUrl: null,
  },
  {
    id: "rufai",
    name: "Rufai Hamzat",
    username: "DLUHAM",
    role: "member",
    isSecretary: false,
    isCorps: false,
    color: "#1f7fa8",
    phone: "+234 80 3489 5621",
    designation: "Systems & Process Officer",
    gradeLevel: "GL 09",
    sex: "Male",
    stateOfOrigin: "Kano",
    dateJoined: "2020-09-08",
    photoUrl: null,
  },
  {
    id: "busari",
    name: "Busari Qudus",
    username: "DLUQUD",
    role: "member",
    isSecretary: false,
    isCorps: false,
    color: "#5a4413",
    phone: "+234 81 2388 6412",
    designation: "Studio & Production Officer",
    gradeLevel: "GL 08",
    sex: "Male",
    stateOfOrigin: "Lagos",
    dateJoined: "2021-02-11",
    photoUrl: null,
  },
  {
    id: "omolara",
    name: "Omolara Olaiya",
    username: "DLUOLA",
    role: "member",
    isSecretary: false,
    isCorps: false,
    color: "#193b34",
    phone: "+234 80 3540 9238",
    designation: "Virtual Programmes Officer",
    gradeLevel: "GL 09",
    sex: "Female",
    stateOfOrigin: "Ondo",
    dateJoined: "2020-05-04",
    photoUrl: null,
  },
  {
    id: "omolola",
    name: "Omolola Ajayi",
    username: "DLUAJA",
    role: "member",
    isSecretary: false,
    isCorps: false,
    color: "#7a4b1e",
    phone: "+234 90 2401 2487",
    designation: "Training & Curriculum Officer",
    gradeLevel: "GL 10",
    sex: "Female",
    stateOfOrigin: "Osun",
    dateJoined: "2018-11-19",
    photoUrl: null,
  },
  {
    id: "oyindamola",
    name: "Oyindamola Adesara",
    username: "DLUADE",
    role: "member",
    isSecretary: true,
    isCorps: false,
    color: "#8a6c19",
    phone: "+234 903 999 7601",
    designation: "Unit Secretary",
    gradeLevel: "GL 08",
    sex: "Female",
    stateOfOrigin: "Ekiti",
    dateJoined: "2021-06-01",
    photoUrl: null,
  },
  {
    id: "okikiola",
    name: "Okikiola Jefferson",
    username: "DLUJEF",
    role: "member",
    isSecretary: false,
    isCorps: true,
    corpsEnd: "2027-01-15",
    color: "#3a5a1f",
    phone: "+234 80 7872 3310",
    designation: "NYSC Corps Member (IT/LMS Support)",
    gradeLevel: "—",
    sex: "Male",
    stateOfOrigin: "Delta",
    dateJoined: "2026-01-15",
    photoUrl: null,
  },
];

/** Dev-only quick-select roster — never includes password hashes. */
export const DEV_ROSTER = SEED_USERS.map((u) => ({
  id: u.id,
  name: u.name,
  username: u.username,
  role: u.role,
  isSecretary: u.isSecretary,
  isCorps: u.isCorps,
  color: u.color,
}));
